
# Alterar tamamho da fonte
map ctrl+equal  change_font_size all +2.0
map ctrl+minus  change_font_size all -2.0
map ctrl+0      change_font_size all 0

font_family MesloLGS NF
font_size 12.0

#TRANSPARENCIA
dynamic_background_opacity yes
background_opacity 0.7

# Remove título da janela (fica mais "limpo")
window_border_width 0
hide_window_decorations yes
window_padding_width 10

tab_bar_edge top
# Estilos possíveis: fade, slant, separator, powerline, custom, hidden
tab_bar_style powerline
# Se escolheu powerline, você pode mudar o formato da ponta (angled, slanted, round)
tab_powerline_style slanted
# Faz a barra sumir se tiver apenas 1 aba aberta (deixa o terminal mais limpo)
tab_bar_min_tabs 2

# Abre nova aba com Ctrl+T
map ctrl+t new_tab

# Fecha aba atual com Ctrl+W
map ctrl+w close_tab



# BEGIN_KITTY_FONTS
#font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
# Liquid Carbon Transparent
include current-theme.conf
# END_KITTY_THEME
